# Generated by Django 3.0.6 on 2020-10-12 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=8)),
                ('type_of_building', models.CharField(choices=[(1, 'BLOK'), (2, 'APARTAMENTOWIEC'), (3, 'WIEŻOWIEC'), (4, 'SZEREGÓWKA'), (5, 'KAMIENICA'), (6, 'DOM WOLNOSTOJĄCY'), (7, 'LOFT'), (8, 'INNE')], default='BLOK', max_length=15)),
                ('material_of_building', models.CharField(choices=[(1, 'CEGŁA'), (2, 'DREWNO'), (3, 'WIELKA PŁYTA'), (4, 'PUSTAK'), (5, 'BETON'), (6, 'ŻELBET'), (6, 'INNE')], default='WIELKA PŁYTA', max_length=15)),
                ('year_of_building', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('number_of_floors', models.IntegerField()),
                ('max_floor', models.IntegerField()),
                ('free_from', models.DateTimeField(blank=True)),
                ('garage', models.BooleanField(default=False)),
                ('parking_slot', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('main_photo', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('reserved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Owner.Owner')),
            ],
        ),
    ]
