# Generated by Django 3.0.6 on 2020-10-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estates', '0002_auto_20201016_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='material_of_building',
            field=models.IntegerField(choices=[(1, 'CEGŁA'), (2, 'DREWNO'), (3, 'WIELKA PŁYTA'), (4, 'PUSTAK'), (5, 'BETON'), (6, 'ŻELBET'), (6, 'INNE')], default='INNE'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='type_of_building',
            field=models.IntegerField(choices=[(1, 'BLOK'), (2, 'APARTAMENTOWIEC'), (3, 'WIEŻOWIEC'), (4, 'SZEREGÓWKA'), (5, 'KAMIENICA'), (6, 'DOM WOLNOSTOJĄCY'), (7, 'LOFT'), (8, 'INNE')], default='INNE'),
        ),
    ]
